spring.application.name=shoplite-backend
server.port=${PORT:8080}

app.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html

app.flutterwave.secret-key=${FLUTTERWAVE_SECRET_KEY}
app.flutterwave.public-key=${FLUTTERWAVE_PUBLIC_KEY}
app.flutterwave.encryption-key=${FLUTTERWAVE_ENCRYPTION_KEY}
app.flutterwave.webhook-hash=${FLUTTERWAVE_WEBHOOK_HASH}

app.frontend.url=${FRONTEND_URL}

# Email (SMTP)
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.password-reset.token-expiration-minutes=30
